#! /bin/bash

cp -r ../adult_circulatory .
cp -r ../adult_foregut .
cp -r ../adult_mesoderm.mapping1 .
cp -r ../adult_muscle .
cp -r ../adult_midgut .
cp -r ../adult_pns .
cp -r ../adult_somatic_muscle .
cp -r ../amnioserosa.mapping1 .
cp -r ../blastoderm.mapping1 .
cp -r ../cardiac.mapping1 .
cp -r ../emb-larv_excretory .
cp -r ../emb-larv_fat_body .
cp -r ../emb-larv_hindgut .
cp -r ../embryonic_muscle .
cp -r ../embryonic_somatic_muscle .
cp -r ../embryonic_trachea .
cp -r ../eye_disc .
cp -r ../eye.mapping1 .
cp -r ../malpig.mapping1 .
cp -r ../mesectoderm.mapping1 .
cp -r ../mesoderm.mapping1 .
cp -r ../antennal_lobe .
cp -r ../disc.mapping2 .
cp -r ../emb-larv_circulatory_system .
cp -r ../emb-larv_foregut .
cp -r ../emb-larv_visceral .
cp -r ../emb-larval_opticlobe .
cp -r ../embryonic_epidermis .
cp -r ../embryonic_midgut .
cp -r ../embryonic_sense_organ .
cp -r ../embryonic_salivary .
cp -r ../fat_body.mapping1 .
cp -r ../female_reproductive .
cp -r ../haltere_disc .
cp -r ../leg_disc .
cp -r ../myoblast .
cp -r ../mapping1.dorsal_ectoderm .
cp -r ../mapping1.ectoderm .
cp -r ../mapping2.ectoderm .
cp -r ../mapping1.glia .
cp -r ../mapping2.glia .
cp -r ../mapping2.mesoderm .
cp -r ../mapping1.salivary_gland .
cp -r ../mapping1.somatic_muscle .
cp -r ../mapping1.tracheal_system .
cp -r ../mapping1.ventral_ectoderm .
cp -r ../mapping1.visceral_mesoderm .
cp -r ../mapping2.wing .
